### ISSUE TITLE
[Bug]: Broken links in the Modules page

### ISSUE THREAD

**Issue by ngryman** [ConduitPlatform/Conduit-Website#120]
### Checklist

- [X] I confirm this issue affects the latest version of Conduit-Website available in `main`.
- [X] I agree to follow the [Code of Conduct](https://github.com/ConduitPlatform/Conduit-Website/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [Issue Tracker](https://github.com/ConduitPlatform/Conduit-Website/issues) for a bug that matches the one I want to file, without success.
- [X] This issue is not related to the [Conduit](https://github.com/ConduitPlatform/Conduit) backend.
- [X] This issue is not related to the [Conduit Admin Panel](https://github.com/ConduitPlatform/Conduit-UI) user interface.

### Describe the Bug

Official modules links are broken in https://getconduit.dev/docs/modules.

### Expected Behavior

The should work.

### How to Reproduce

1. Go to https://getconduit.dev/docs/modules.
2. Click on any of the links.

**Comment by kon14** [comment]
Hey, thanks for reporting.
I could only reproduce this in Safari and introduced a fix in #119.

You can find a preview of the fix [here](https://deploy-preview-119--mystifying-borg-373afd.netlify.app/docs/modules/).
Please let me know if this resolved the issue.
